<?php

function carusel_block_info() {
	$info['carusel'.'0'] = array(
		'info' => t('Carusel.'),
		'cache' => DRUPAL_CACHE_PER_PAGE,
		'region' => t('content'));
	return $info;
}
function carusel_block_configure($delta = '') {
	$result = db_query("SELECT type, name FROM node_type");
	$contentTypes = array();
	$contentTypes['all'] = 'All';
	foreach ($result as $record) {
		$contentTypes[$record->type] = t($record->name);
	}
	
	$form = array();
	$form[$delta.'_max_count'] = array(
		'#type' => 'select',
		'#title' => t('Максимальное колличество новостей в карусели.'),
		'#default_value' => variable_get($delta.'_max_count', 4),
		'#options' => drupal_map_assoc(array(2, 3, 4, 5, 6, 7, 8, 9, 10)),
    );
	$form[$delta.'_content_type'] = array(
		'#type' => 'select',
		'#title' => t('Выберите тип контента отображаемые в блоке.'),
		'#default_value' => variable_get($delta.'_content_type', 'all'),
		'#options' => $contentTypes,
    );
	$form[$delta.'_aspect_ratio'] = array(
		'#type' => 'select', 
		'#title' => t('Соотношение сторон блока'), 
		'#default_value' => variable_get($delta.'_aspect_ratio', 0),
		'#description' => t('Укажите соотношение сторон блока'),
		'#options' => array(0=>'3x4', 1=>'2x3', 2=>'16x9', 3=>'1.85x1', 4=>'2.39x1'),
	);
	return $form;
}
function carusel_block_save($delta = '', $edit = array()) {
	variable_set($delta.'_max_count', $edit[$delta.'_max_count']);
	variable_set($delta.'_content_type', $edit[$delta.'_content_type']);
	variable_set($delta.'_aspect_ratio', $edit[$delta.'_aspect_ratio']);
}
function carusel_block_view($delta = '') {
/*
SELECT node.nid, node.title, field_data_field_image.field_image_alt, field_data_field_image.field_image_width,
	field_data_field_image.field_image_height, file_managed.uri
FROM node
	INNER JOIN field_data_field_image ON node.nid=field_data_field_image.entity_id 
	INNER JOIN file_managed ON field_data_field_image.field_image_fid=file_managed.fid 
WHERE type='article'
	AND node.vid=field_data_field_image.revision_id
LIMIT $pageMaxCount
*/
	$pageMaxCount = intval(variable_get($delta.'_max_count', 4));
	$aspect_ratio_id = intval(variable_get($delta.'_aspect_ratio', 0));
	$contentType = t(variable_get($delta.'_content_type', 'all'));
	if ($contentType == 'all') {
		$queryWhere = 'WHERE node.vid=field_data_field_image.revision_id ';
	}else{
		$queryWhere = "WHERE type='$contentType' AND node.vid=field_data_field_image.revision_id ";
	}
	switch ($aspect_ratio_id) {
		case 0:
			//$aspect_ratio = 'block.clientWidth*3/4';
			drupal_add_css('
@media (min-width: 768px) {#'.$delta.', #'.$delta.' .item {height: 562px;}}
@media (min-width: 992px) {#'.$delta.', #'.$delta.' .item {height: 728px;}}
@media (min-width: 1200px) {#'.$delta.', #'.$delta.' .item {height: 878px;}}', 'inline');
			break;
		case 1:
			//$aspect_ratio = 'block.clientWidth*2/3';
			drupal_add_css('
@media (min-width: 768px) {#'.$delta.', #'.$delta.' .item {height: 500px;}}
@media (min-width: 992px) {#'.$delta.', #'.$delta.' .item {height: 646px;}}
@media (min-width: 1200px) {#'.$delta.', #'.$delta.' .item {height: 780px;}}', 'inline');
			break;
		case 2:
			//$aspect_ratio = 'block.clientWidth*9/16';
			drupal_add_css('
@media (min-width: 768px) {#'.$delta.', #'.$delta.' .item {height: 422px;}}
@media (min-width: 992px) {#'.$delta.', #'.$delta.' .item {height: 546px;}}
@media (min-width: 1200px) {#'.$delta.', #'.$delta.' .item {height: 658px;}}', 'inline');
			break;
		case 3:
			//$aspect_ratio = 'block.clientWidth/1.85';
			drupal_add_css('
@media (min-width: 768px) {#'.$delta.', #'.$delta.' .item {height: 405px;}}
@media (min-width: 992px) {#'.$delta.', #'.$delta.' .item {height: 524px;}}
@media (min-width: 1200px) {#'.$delta.', #'.$delta.' .item {height: 632px;}}', 'inline');
			break;
		case 4:
			//$aspect_ratio = 'block.clientWidth/2.39';
			drupal_add_css('
@media (min-width: 768px) {#'.$delta.', #'.$delta.' .item {height: 314px;}}
@media (min-width: 992px) {#'.$delta.', #'.$delta.' .item {height: 406px;}}
@media (min-width: 1200px) {#'.$delta.', #'.$delta.' .item {height: 490px;}}', 'inline');
			break;
	}
	$result = db_query("
SELECT node.nid, node.title, field_data_field_image.field_image_alt, field_data_field_image.field_image_width,
	field_data_field_image.field_image_height, file_managed.uri
FROM node
	INNER JOIN field_data_field_image ON node.nid=field_data_field_image.entity_id 
	INNER JOIN file_managed ON field_data_field_image.field_image_fid=file_managed.fid 
$queryWhere
LIMIT $pageMaxCount");
	$nids = array();
	foreach ($result as $record) {
		$nids[] = $record;
	}
	
	$indicators = '<li data-target="#'.$delta.'" data-slide-to="0" class="active"></li> ';
	for($i=1; $i<count($nids); $i++) {
		$indicators .= '<li data-target="#'.$delta.'" data-slide-to="'.intval($i).'"></li> ';
	}
	
	$items = '<div class="item active"><img src="'.t(file_create_url($nids[0]->uri)).'"><div class="carousel-caption"><h3>'.t($nids[0]->title).'</h3></div></div>';
	for($i=1; $i<count($nids); $i++) {
		$items .= '<div class="item"><img src="'.t(file_create_url($nids[$i]->uri)).'"><div class="carousel-caption"><h3>'.t($nids[$i]->title).'</h3></div></div>';
	}


	$view['subject'] = NULL;
	$view['content'] = '
	<div id="'.$delta.'" class="carousel slide" data-ride="carousel">
		<ol class="carousel-indicators">'.$indicators.'</ol>
		<div class="carousel-inner" role="listbox">'.$items.'</div>
		<a class="left carousel-control" href="#'.$delta.'" role="button" data-slide="prev">
			<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span><span class="sr-only">Назад</span>
		</a>
		<a class="right carousel-control" href="#'.$delta.'" role="button" data-slide="next">
			<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span><span class="sr-only">Вперед</span>
		</a>
	</div>';
	/*<script>
	window.onresize = function(event) {
		var block = document.getElementById("'.$delta.'"), items, height = "";
		block.style.height = height = Math.floor('.$aspect_ratio.')+"px";
		items = block.getElementsByClassName("item");
		for(var i=0, length=items.length; i<length; i++) items[i].style.height = height;
	};
	(function(){
		var block = document.getElementById("'.$delta.'"), items, height = "";
		block.style.height = height = Math.floor('.$aspect_ratio.')+"px";
		items = block.getElementsByClassName("item");
		for(var i=0, length=items.length; i<length; i++) items[i].style.height = height;
	})();
	</script>';*/
	return $view;
}